/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DatastoreObservation struct {

	// The connectivity status of the datastore. If this is false,
	// some other computed attributes may be out of date.
	// The connectivity status of the datastore. If this is false, some other computed attributes may be out of date.
	Accessible *bool `json:"accessible,omitempty" tf:"accessible,omitempty"`

	// Maximum capacity of the datastore, in megabytes.
	// Maximum capacity of the datastore, in MB.
	Capacity *float64 `json:"capacity,omitempty" tf:"capacity,omitempty"`

	// Available space of this datastore, in megabytes.
	// Available space of this datastore, in MB.
	FreeSpace *float64 `json:"freeSpace,omitempty" tf:"free_space,omitempty"`

	// The managed object reference ID of the datastore.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The current maintenance mode state of the datastore.
	// The current maintenance mode state of the datastore.
	MaintenanceMode *string `json:"maintenanceMode,omitempty" tf:"maintenance_mode,omitempty"`

	// If true, more than one host in the datacenter has
	// been configured with access to the datastore.
	// If true, more than one host in the datacenter has been configured with access to the datastore.
	MultipleHostAccess *bool `json:"multipleHostAccess,omitempty" tf:"multiple_host_access,omitempty"`

	// Indicates that this NAS volume is a protocol endpoint.
	// This field is only populated if the host supports virtual datastores.
	// Indicates that this NAS volume is a protocol endpoint. This field is only populated if the host supports virtual datastores.
	ProtocolEndpoint *bool `json:"protocolEndpoint,omitempty" tf:"protocol_endpoint,omitempty"`

	// The unique locator for the datastore.
	// The unique locator for the datastore.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Total additional storage space, in megabytes,
	// potentially used by all virtual machines on this datastore.
	// Total additional storage space, in MB, potentially used by all virtual machines on this datastore.
	UncommittedSpace *float64 `json:"uncommittedSpace,omitempty" tf:"uncommitted_space,omitempty"`
}

type DatastoreParameters struct {

	// Access mode for the mount point. Can be one of
	// readOnly or readWrite. Note that readWrite does not necessarily mean
	// that the datastore will be read-write depending on the permissions of the
	// actual share. Default: readWrite. Forces a new resource if changed.
	// Access mode for the mount point. Can be one of readOnly or readWrite.
	// +kubebuilder:validation:Optional
	AccessMode *string `json:"accessMode,omitempty" tf:"access_mode,omitempty"`

	// Map of custom attribute ids to attribute
	// value strings to set on datasource resource. See
	// here for a reference on how to set values
	// for custom attributes.
	// A list of custom attributes to set on this resource.
	// +kubebuilder:validation:Optional
	CustomAttributes map[string]*string `json:"customAttributes,omitempty" tf:"custom_attributes,omitempty"`

	// The managed object
	// ID of a datastore cluster to put this datastore in.
	// Conflicts with folder.
	// The managed object ID of the datastore cluster to place the datastore in.
	// +kubebuilder:validation:Optional
	DatastoreClusterID *string `json:"datastoreClusterId,omitempty" tf:"datastore_cluster_id,omitempty"`

	// The relative path to a folder to put this datastore in.
	// This is a path relative to the datacenter you are deploying the datastore to. Conflicts with
	// datastore_cluster_id.
	// The path to the datastore folder to put the datastore in.
	// +kubebuilder:validation:Optional
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// The managed object IDs of
	// the hosts to mount the datastore on.
	// The managed object IDs of the hosts to mount the datastore on.
	// +kubebuilder:validation:Required
	HostSystemIds []*string `json:"hostSystemIds" tf:"host_system_ids,omitempty"`

	// The name of the datastore. Forces a new resource if
	// changed.
	// The name of the datastore.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// The hostnames or IP addresses of the remote
	// server or servers. Only one element should be present for NFS v3 but multiple
	// can be present for NFS v4.1. Forces a new resource if changed.
	// The hostnames or IP addresses of the remote server or servers. Only one element should be present for NFS v3 but multiple can be present for NFS v4.1.
	// +kubebuilder:validation:Required
	RemoteHosts []*string `json:"remoteHosts" tf:"remote_hosts,omitempty"`

	// The remote path of the mount point. Forces a new
	// resource if changed.
	// The remote path of the mount point.
	// +kubebuilder:validation:Required
	RemotePath *string `json:"remotePath" tf:"remote_path,omitempty"`

	// The security type to use when using NFS v4.1.
	// Can be one of AUTH_SYS, SEC_KRB5, or SEC_KRB5I. Forces a new resource
	// if changed.
	// The security type to use.
	// +kubebuilder:validation:Optional
	SecurityType *string `json:"securityType,omitempty" tf:"security_type,omitempty"`

	// The IDs of any tags to attach to this resource. See
	// here for a reference on how to apply tags.
	// A list of tag IDs to apply to this object.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The type of NAS volume. Can be one of NFS (to denote
	// v3) or NFS41 (to denote NFS v4.1). Default: NFS. Forces a new resource if
	// changed.
	// The type of NAS volume. Can be one of NFS (to denote v3) or NFS41 (to denote NFS v4.1).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// DatastoreSpec defines the desired state of Datastore
type DatastoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DatastoreParameters `json:"forProvider"`
}

// DatastoreStatus defines the observed state of Datastore.
type DatastoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatastoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Datastore is the Schema for the Datastores API. Provides a vSphere NAS datastore resource. This can be used to mount a NFS share as a datastore on a host.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vsphere}
type Datastore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DatastoreSpec   `json:"spec"`
	Status            DatastoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatastoreList contains a list of Datastores
type DatastoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Datastore `json:"items"`
}

// Repository type metadata.
var (
	Datastore_Kind             = "Datastore"
	Datastore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Datastore_Kind}.String()
	Datastore_KindAPIVersion   = Datastore_Kind + "." + CRDGroupVersion.String()
	Datastore_GroupVersionKind = CRDGroupVersion.WithKind(Datastore_Kind)
)

func init() {
	SchemeBuilder.Register(&Datastore{}, &DatastoreList{})
}
